
import {
  Seafoodokra, 
  Hero,
  Whitesoup,
  whiterice,
  Wheat,
  samosa,
  Redstew,
  Plantainflour,
  Owhosoup,
  Oha,
  Ogbono,
  Oat,
  Nativerice,
  mokyJollofrice,
  Groundnutfish,
  Gbegiri,
  Fufu,
  food9,
  food8,
  food7,
  food6,
  Friedrice,
  Sharwama,
  food3,
  food2,
  food1,
  Fishermansoup,
  fish,
  Ewedu,
  Eforiro,
  Edidiakong,
  Eba,
  Coconutrice,
  chicken,
  goat,
  Poundedyam, 
  cake, 
  egusi, 
  Bitterleaf, 
  Afang, 
  Blacksoup, 
  Bangasoup, 
  Amala, 
  Asunrice, 
  Bangarice,
  Semo,
  Vegetablerice,
  PuffPuff,
  nwokobi,
  ewa,
  Bolefish,
  Beansplantain,
  FriedBeans,
  Plantainporridge,
  Yamporridge,
  Isewu,
  Testimonials1,
  Testimonials2,
  Testimonials3,
  Testimonials4,
 } from './Assets/asset';


const mealCategory = [
  {
    name: 'Soup',
    img: egusi,
},
{
  name: 'PepperSoup',
  img: goat
},
{
  name: 'Confectionaries',
  img: cake,
},   
{
  name: 'Swallow',
  img: Poundedyam,
},
{
  name: 'Rice',
  img: Friedrice,
},
{
  name: 'Others',
  img: food3,
},

]
    
const mealList = [
  {
    id: 1,
    img: Seafoodokra,
    name: "Seafood Okra",
    description: "Delicious Nigerian soup made with melon seeds and assorted meats",
    price: 10.99, // Price per liter
    category: 'Soup',
  },
  {
    id: 2,
    img: egusi,
    name: "Egusi",
    description: "Nutritious Nigerian soup made with assorted leafy vegetables and proteins",
    price: 12.99,
    category: 'Soup',
  },
  {
    id: 3,
    img: Redstew,
    name: "Red Stew",
    description: "Traditional Nigerian soup made with okra and seafood or meat",
    price: 9.99,
    category: 'Soup',
    
  },
  {
    id: 4,
    img: Ogbono,
    name: "Ogbono",
    description: "Popular West African dish made with rice, tomatoes, and spices",
    price: 8.99,
    category: 'Soup',
  },
{
  id: 5,
  img: Eforiro,
  name: "Efo riro",
  description: "Delicious Nigerian soup made with melon seeds and assorted meats",
  price: 10.99, 
  category: 'Soup',
},
{
  id: 6,
  img: Ewedu,
  name: "Ewedu",
  description: "Nutritious Nigerian soup made with assorted leafy vegetables and proteins",
  price: 12.99,
  category: 'Soup',
},
{
  id: 7,
  img: Bitterleaf,
  name: "Bitter leaf",
  description: "Traditional Nigerian soup made with okra and seafood or meat",
  price: 9.99,
  category: 'Soup',
},
{
  id: 8,
  img: Whitesoup,
  name: "White Soup",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 8.99,
  category: 'Soup',
},
{
  id: 9,
  img: Edidiakong,
  name: "Edidiakong",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 3.99,
  category: 'Soup',
},
{
  id: 10,
  img: Afang,
  name: "Afang",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 4.59,
  category: 'Soup',
},
{
  id: 11,
  img: Oha,
  name: "Oha",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 6.09,
  category: 'Soup',
},
{
  id: 12,
  img: Blacksoup,
  name: "Black soup",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 3.29,
  category: 'Soup',
},
{
  id: 13,
  img: Bangasoup,
  name: "Banga Soup",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 2.89,
  category: 'Soup',
},
{
  id: 14,
  img: Owhosoup,
  name: "Owho soup",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 8.0,
  category: 'Soup',
},
{
  id: 15,
  img: Gbegiri,
  name: "Gbegiri",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 4.19,
  category: 'Soup',
},
{
  id: 16,
  img: Fishermansoup,
  name: "Fisherman Soup",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 9.32,
  category: 'Soup',
},
{
  id: 17,
  img: Groundnutfish,
  name: "Groundnut fish",
  description: "Popular West African dish made with rice, tomatoes, and spices",
  price: 4.45,
  category: 'Soup',
},
{
  id: 18,
  img: fish,
  name: "Fish",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 3.90,
  category:'PepperSoup',
},
{
  id: 19,
  img: goat,
  name: "Goat",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 2.39,
  category:'PepperSoup',
},
{
  id: 20,
  img: chicken,
  name: "Chicken",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 6.04,
  category:'PepperSoup',
},
{
  id: 21,
  img: Sharwama,
  name: "Sharwama",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 8.99,
  category:'Confectionaries',
},
{
  id: 22,
  img: cake,
  name: "Cakes",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.89,
  category:'Confectionaries',
},
{
  id: 23,
  img: samosa,
  name: "Samosa",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.09,
  category:'Confectionaries',
},
{
  id: 24,
  img: PuffPuff,
  name: " Puff puff",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 3.79,
  category:'Confectionaries',
},
{
  id: 25,
  img:Isewu,
  name: "Ise Ewu",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 3.29,
  category:'Others',
},
{
  id: 26,
  img: nwokobi,
  name: "Nwokobi",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 6.79,
  category:'Others',
},
{
  id: 27,
  img: ewa,
  name: "Ewa aganyin",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.49,
  category:'Others',
},
{
  id: 28,
  img: Beansplantain,
  name: "Beans and Plantain",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 3.59,
  category:'Others',
},
{
  id: 29,
  img: Bolefish,
  name: "Bole and fish",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 3.59,
  category:'Others',
},
{
  id: 30,
  img: FriedBeans,
  name: "Fried beans",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 8.94,
  category:'Others',
},
{
  id: 31,
  img: Plantainporridge,
  name: "Plantain Porridge",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.59,
  category:'Others',
},
{
  id: 32,
  img: Yamporridge,
  name: "Yam Porridge",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.69,
  category:'Others',
},
{
  id: 33,
  img: Nativerice,
  name: "Native rice",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 5.56,
  category:'Rice',
},
{
  id: 34,
  img: Asunrice,
  name: "Asun rice",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.09,
  category:'Rice',
},
{
  id: 35,
  img: whiterice,
  name: "White rice",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.79,
  category:'Rice',
},
{
  id: 36, 
  img: mokyJollofrice,
  name: "Smoky Jollof rice",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.98,
  category:'Rice',
},
{
  id: 37,
  img: Vegetablerice,
  name: "Vegetable rice",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 6.95,
  category:'Rice',
},
{
  id: 38,
  img: Coconutrice,
  name: "Coconut Rice",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.59,
  category:'Rice',
},
{
  id: 39,
  img: Bangarice,
  name: "Banga rice",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 0.69,
  category:'Rice',
},
{
  id: 40,
  img: Friedrice,
  name: "Fried rice",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.95,
  category:'Rice',
},

{
  id: 41,
  img: Eba,
  name: "Eba (garri)",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 6.05,
  category:'Swallow',
},
{
  id: 42,
  img: Fufu,
  name: "Fufu",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 3.59,
  category:'Swallow',
},
{
  id: 43,
  img: Amala,
  name: "Amala",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 1.29,
  category:'Swallow',
},
{
  id: 44, 
  img: Poundedyam,
  name: "Pounded yam",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.79,
  category:'Swallow',
},
{
  id: 45,
  img: Wheat,
  name: "Wheat",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 4.09,
  category:'Swallow',
},
{
  id: 46,
  img: Semo,
  name: "Semo",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 8.99,
  category:'Swallow',
},
{
  id: 47,
  img: Plantainflour,
  name: "Plantain flour",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 8.99,
  category:'Swallow',
},
{
  id: 48,
  img: Oat,
  name: "Oat",
  description: "LorempSum LorempSum LorempSum LorempSum",
  price: 2.79,
  category:'Swallow',
},
]

export const testimonials = [
  {
    id: 1,
    name: "John Doe",
    location: "Gwarimpa",
    title: "A Wonderful Experience",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget justo nec elit laoreet aliquet. Vivamus lobortis odio et quam condimentum, ut hendrerit ligula faucibus. Nulla facilisi.",
    date: "April 10, 2024",
    time: "10:00 AM",
    avatar: Testimonials4,
  },
  {
    id: 2,
    name: "Mitcheal Lanes",
    location: "Maitama",
    title: "A Wonderful Experience",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget justo nec elit laoreet aliquet. Vivamus lobortis odio et quam condimentum, ut hendrerit ligula faucibus. Nulla facilisi.",
    date: "May 15, 2024",
    time: "10:00 PM",
    avatar: Testimonials3,
  },
  {
    id: 3,
    name: "Mahmud Albato",
    location: "Jabi",
    title: "Nice Taste",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget justo nec elit laoreet aliquet. Vivamus lobortis odio et quam condimentum, ut hendrerit ligula faucibus. Nulla facilisi.",
    date: "July 10, 2022",
    time: "03:00 PM",
    avatar: Testimonials2,
  },
  {
    id: 4,
    name: "Rose Elisha",
    location: "Central Area",
    title: "A Meal for All",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget justo nec elit laoreet aliquet. Vivamus lobortis odio et quam condimentum, ut hendrerit ligula faucibus. Nulla facilisi.",
    date: "Dec 25 2023",
    time: "04:34 AM",
    avatar: Testimonials1,
  },
];
  
const quantities = [
    { label: "1/2 liter", value: 0.5 },
    { label: "1 liter", value: 1 },
    { label: "2 liters", value: 2 },
    { label: "3 liters", value: 3 },
    { label: "4 liters", value: 4 },
    
  ];
  
  const deliveryOptions = [
    { label: "Pick Up", value: "pick-up" },
    { label: "Drop Off", value: "drop-off" },
  ];
  
  export { 
    mealList, 
    mealCategory,
    quantities, 
    deliveryOptions,
    egusi, 
    Poundedyam, 
    cake, 
    food3, 
    Friedrice, 
    goat,
    Seafoodokra, 
    Hero,
    Whitesoup,
    whiterice,
    Wheat,
    samosa,
    Redstew,
    Plantainflour,
    Owhosoup,
    Oha,
    Ogbono,
    Oat,
    Nativerice,
    mokyJollofrice,
    Groundnutfish,
    Gbegiri,
    Fufu,
    food9,
    food8,
    food7,
    food6,
    Sharwama,
    food2,
    food1,
    Fishermansoup,
    fish,
    Ewedu,
    Eforiro,
    Edidiakong,
    Eba,
    Coconutrice, 
    Bitterleaf, 
    Afang, 
    Blacksoup, 
    Bangasoup, 
    Amala, 
    Asunrice, 
    Bangarice,
    Semo,
    Vegetablerice,
    nwokobi,
    ewa,
    Bolefish,
    Beansplantain,
    FriedBeans,
    Plantainporridge,
    Yamporridge,
    Isewu,
    Testimonials1,
    Testimonials2,
    Testimonials3,
    Testimonials4,
  };






 


